[profile.default]
solc = '0.8.23'
vm_version = 'paris'                   # Required for L2s (Optimism, Arbitrum, etc.)
sizes = true
verbosity = 3                           # display errors
optimizer_runs = 1000
block_number = 14126430
block_timestamp = 1643802347
runs = 4096
fs_permissions = [{ access = "read", path = "lib/juice-contracts-v4/broadcast/Deploy.s.sol" }, { access = "read", path = "lib/juice-721-hook/broadcast/Deploy.s.sol" }] # Get the deployment addresses to base the hook on.

[invariant] 
fail_on_revert = false

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
